version: 2
updates:
  # 1. Security updates — daily
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    reviewers:
      - 'ONS-Digital/maintainers'

  # 2. Routine version bumps — weekly
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 5
    labels:
      - dependencies
    reviewers:
      - 'ONS-Digital/maintainers'

  # 3. GitHub Actions workflow updates — monthly
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    reviewers:
      - 'ONS-Digital/maintainers'
