version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    reviewers:
      - 'ONSDigital/maintainers'
    labels:
      - 'dependencies'
      - 'security'
    # Auto‑merge patch and minor updates once CI passes
    automerge: true
