# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: npm # ecosystem to update
    directory: '/' # location of package manifests
    schedule:
      interval: weekly # check for updates once a week
    open-pull-requests-limit: 5 # maximum number of open PRs at any time
